version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/pink-collar-backend
files_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/pink-collar-backend
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/clean_old_files.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu

